# Generated by Django 3.2.9 on 2021-12-08 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Такое название, уже есть. Назовите другим именем'}, max_length=200, unique=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст ')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
